### ISSUE TITLE
SEGFAULT in reex when running for a couple of seconds

### ISSUE THREAD

**Issue by jhx0** [rilysh/reex#1]
Hi @rilysh! :)

When running **reex** for a couple of seconds, the program SEGFAULT's.
I narrowed it down a little by adding debugging capabilities (**FLAGS**):
```Make
...
FLAGS=-msse -msse2 -mavx -g -ggdb -O0
...
```
## Output:
```Bash
$ gdb ./reex
(gdb) r --eall
Starting program: /home/x/Downloads/reex/reex --eall
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Running [73817] with 6 logical core(s)
[New Thread 0x7ffff7db2700 (LWP 73818)]
[New Thread 0x7ffff75b1700 (LWP 73819)]
[New Thread 0x7ffff6db0700 (LWP 73820)]
[New Thread 0x7ffff65af700 (LWP 73821)]
[New Thread 0x7ffff5dae700 (LWP 73822)]
[New Thread 0x7ffff55ad700 (LWP 73823)]
[Thread 0x7ffff75b1700 (LWP 73819) exited]
[Thread 0x7ffff55ad700 (LWP 73823) exited]
[Thread 0x7ffff7db2700 (LWP 73818) exited]
[Thread 0x7ffff5dae700 (LWP 73822) exited]
[Thread 0x7ffff6db0700 (LWP 73820) exited]
[Thread 0x7ffff65af700 (LWP 73821) exited]

Thread 1 "reex" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f9b04a in __pthread_cancel (th=140737351722752) at pthread_cancel.c:33
33	pthread_cancel.c: No such file or directory.
(gdb) bt
#0  0x00007ffff7f9b04a in __pthread_cancel (th=140737351722752) at pthread_cancel.c:33
#1  0x0000555555562d3d in multi_thread_attach (fn=0x5555555553d0 <avx_f32_add>, iter=98352000) at reex.c:85
#2  0x0000555555562dc0 in avx_sp () at reex.c:101
#3  0x0000555555563397 in main (argc=2, argv=0x7fffffffe778) at reex.c:280
```
## Output
```Bash
hp ~/Downloads/reex $ time ./reex --eall
Running [74593] with 6 logical core(s)
Segmentation fault

real	0m2.676s
user	0m15.802s
sys	0m0.008s
```
## System
OS: **Debian 11** (**Bullseye**) **amd64**
Compiler: **GCC**
```Bash
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 10.2.1-6' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-10-Km9U7s/gcc-10-10.2.1/debian/tmp-gcn/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-mutex
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Debian 10.2.1-6)
```
## CPU Info
```Bash
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          6
On-line CPU(s) list:             0-5
Thread(s) per core:              1
Core(s) per socket:              6
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
Stepping:                        10
CPU MHz:                         800.024
CPU max MHz:                     4400.0000
CPU min MHz:                     800.0000
BogoMIPS:                        6000.00
Virtualization:                  VT-x
L1d cache:                       192 KiB
L1i cache:                       192 KiB
L2 cache:                        1.5 MiB
L3 cache:                        9 MiB
NUMA node0 CPU(s):               0-5
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Retbleed:          Mitigation; IBRS
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflus
                                 h dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constan
                                 t_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aper
                                 fmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16
                                  xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave
                                  avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti 
                                 ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc
                                 _adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushop
                                 t intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_noti
                                 fy hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
```
## Notes
I'm not quite sure where the problem comes from - i only have limited experience with POSIX Threads.
Maybe you see the issue directly. :)

**Comment by rilysh** [comment]
Hello! This seems to be an issue with `pthread_cancel` and if the thread lifetime is already gone, passing the thread id in `pthread_cancel` may cause a segmentation fault.
 
But even without making any changes, I can't able reproduce the error here. Download Debian but still can't. 
#### Image
![image](https://user-images.githubusercontent.com/71683721/217461352-5a52ebbc-5292-4c5d-a227-52bf31dbd936.png)
#### Image (On Debian)
![image](https://user-images.githubusercontent.com/71683721/217461578-3ad14e99-074d-4bde-b002-ae0c321c0a46.png)

Also, out of curiosity, but do your PC UEFI has a hyper-threading option? If yes, is it disabled there?
i5-9500 CPU has hyper-threading "disabled" on the CPU microcode level. 
Spec: https://www.intel.com/content/www/xa/en/products/sku/134895/intel-core-i59500-processor-9m-cache-up-to-4-40-ghz/specifications.html
#### Image
![image](https://user-images.githubusercontent.com/71683721/217460603-3c302a2a-4a28-423a-8eed-97b9978c4fcf.png)

I pushed some changes here, if it's an issue with `pthread_cancel` then this should fix the issue.

**Comment by jhx0** [comment]
Hi @rilysh!

I can confirm that there is no issue anymore - the commit fixed it for me:
```
hp ~/Downloads/reex $ ./reex --eall
Running [9276] with 6 logical core(s)
```
I left reex running for a couple of minutes.

Indeed, the CPU does not have Hyperthreading - there are only 6 cores without HT.
I think this is the culprit on this system. I will test the code also on my Dell XPS - which has HT enabled.
At this point i think i can close the issue since this is hardware related. (At least in this very case)

Thanks for investigating the issue! ;)

Closing the issue since the issue is fixed.

**Comment by rilysh** [comment]
Nice to see it's fixed :)

I was also thinking about graphics intensive work, specifically for iGPU which will heat up the CPU even more but I quickly figure it out there's no ABI that is useful unless use of existing libraries like OpenGL for shaders but it ~~will not run~~ compatibility issues without an iGPU or an external GPU which will remove the whole thing (exact point). Example: If running on Pentium E5400 (SSE, SSE2, no AVX or above, no iGPU)

Cheers!

**Comment by jhx0** [comment]
Stressing the iGPU would be interesting indeed! :)
(Which would for sure load up the entire CPU pretty well)
Maybe OpenGL can be leveraged for that - let's say it might.
Yes, without an iGPU that would pose a problem for sure.

**Comment by rilysh** [comment]
Yup, whenever I'll get some time, I'll add it :)
OpenGL compatibility... most older CPUs don't even have OpenGL support above  than 1.1... (e.g. Intel CPUs which were created before 2010), so... unless we do a test with 1.1 but it will not be the same with high-end systems.

...and AMD doesn't even have that (e.g. AMD FX, Phenom), and today's desktop CPU (by AMD) that doesn't have "G" at the end doesn't have iGPU. (e.g.  *which has* Ryzen 7 4700G, several Athlon products, etc.) 
Found a comment: https://community.amd.com/t5/graphics/why-doesn-t-amd-support-for-opengl/m-p/391293/highlight/true#M62513
> Thankfully most of the better emulators are moving to Vulkan for the same reasons they used to use OpenGL and AMD's GPUs are much better at Vulkan 

This post was from 2018 and since then CPU speedrunning is like skyrocketing (a lot of changes in a short period of time).

**Comment by jhx0** [comment]
Take your time, reex for now works fine for doing some CPU stress testing. ;)
That might make for complex code if there is a need to make checks beforehand. Which in return can be a hassle to implement and make available for all the different CPU variants.
Right, AMD CPU's usually ship without a GPU - i have a Ryzen 3900x here which does not have a intergrated GPU.
Indeed, CPU's evolve quite rapidly nowadays... well, the old single core times are truly gone for sure!
